project:
  title: "nzsss_2022_dems"

editor: visual

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    out.width: '85%'
    fig.align: 'center'
    echo: false
    fig.show: 'hold'
    results: 'hold'
