project:
  title: "NZSSS 2022 DEM poster"

editor: visual

format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 4

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    fig.align: 'center'
    fig.show: 'hold'
    results: 'hold'
    warning: false
    message: false
